### ISSUE TITLE
Does not working with Windows

### ISSUE THREAD

**Issue by virendrapatidar** [ricardoalcocer/alloy-widget-drawermenu#6]
If I use windows instead of views, it won't work.

**Comment by ricardoalcocer** [comment]
Right, it won't work.  You add the Widget to your App's root window and the panels are views.  Even though this Widget works with iOS and Android, I suggest using this module (https://github.com/Tripvi/Ti.DrawerLayout) for Android to get the native drawer layout.  Then again, it's only for Views.

**Comment by virendrapatidar** [comment]
Thanks,

I am using http://gitt.io/component/com.alcoapps.drawermenu and its working with views.

Regards,
Virendra Patidar
Email: virendrapatidar@gmail.com

**Comment by ricardoalcocer** [comment]
Happy to hear.  Make sure you checkout the Android example at: https://github.com/ricardoalcocer/alloy-widget-drawermenu/tree/master/ActionBar%20Demo

**Comment by skuller** [comment]
Hi Ricardo, thanks for the amazing widget! I'm able to use it for iOS and Android. However, could you please elaborate on your previous comment regarding the https://github.com/Tripvi/Ti.DrawerLayout module? Would it be more performant? Since I notice some lagg on my Galaxy S3... specially when doing swipe.

Thanks again!!!

Andres

**Comment by ricardoalcocer** [comment]
Hi,

My comment is regarding Native UI/UX.  As a general rule, you should look
for a native object before trying to create your own.  Android has a native
slide-in drawer available through the Tripvi widget.  iOS has no native
notion of this, so you have to create it your self.

You’ll notice that Android’s implementation (
http://developer.android.com/design/patterns/navigation-drawer.html) leaves
the ActionBar in the same place, and slides the menu in without pushing the
main content area.  This is different to what my widget does, where I
simply move the content area to the right to reveal the menu behind it.

It all boils down to user experience and thinking native.  Ultimately it’s
all up to the developer, but I’d argue that sticking to native controls is
best for your apps adoption, even when it represents that your app will
look different across platforms.  In fact, in most cases, the navigation of
iOS and Android apps will be different by definition, because after all,
both platforms are different.

Make sure you send me a link of your published app so I can add you to the
repo.

Best,

R

On Tue, May 13, 2014 at 4:26 PM, Andres Ramirez notifications@github.comwrote:

> Hi Ricardo, thanks for the amazing widget! I'm able to use it for iOS and
> Android. However, could you please elaborate on your previous comment
> regarding the https://github.com/Tripvi/Ti.DrawerLayout module? Would it
> be more performant? Since I notice some lagg on my Galaxy S3... specially
> when doing swipe.
> 
> Thanks again!!!
> 
> Andres
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ricardoalcocer/alloy-widget-drawermenu/issues/6#issuecomment-43025734
> .

## 

_Ricardo Alcocer_
_Technology Evangelist_
Sunnyvale, CA 94085https://maps.google.com/maps?q=sunnyvale,+ca+94085&hl=en
(408) 901-9604
alco@ricardoalcocer.com
http://myqrkode.com/c/ricardoalcocer

**Comment by skuller** [comment]
Thanks Ricardo :) and again, fantastic job!

**Comment by ricardoalcocer** [comment]
Thanks. Glad to hear.

**Comment by treinberger** [comment]
Ricardo,

thanks for your widget. On Android I encountered a problem using the implementation without any native Controls (just using your widget). When the content Area contains a scrollable element, the widget "steals" the swipe event and the scrollable content element looses it's scrolling momentum. I played around with other events and this seems to work, although it's not perfect. Maybe you've got a better idea:

var setSwipe=function(){
    parent.addEventListener('touchstart',function(e){ 
        x_touchStart = e.x;
        //console.log("touchstart: " + e.x);
    });
    parent.addEventListener('touchend',function(e){ 
        //console.log(x_touchStart + " - " + e.x);
        if (!menuOpen && x_touchStart < Ti.Platform.displayCaps.platformWidth/2 && e.x - x_touchStart > (Ti.Platform.displayCaps.platformWidth/10)) {
            e.cancelBubble = true;
            showhidemenu();
            menuOpen = true;
        } else if (menuOpen && x_touchStart - e.x > (Ti.Platform.displayCaps.platformWidth/10)) {
            e.cancelBubble = true;
            showhidemenu();
            menuOpen = false;
        }
    });
    parent.addEventListener('touchcancel',function(e){ 
        console.log("touchcancel: " + e.x + ":" + e.y);
    });
};

Cheers
Thomas

**Comment by ricardoalcocer** [comment]
Hi Thomas,

That's a good point;  I didn't add the swipe support myself, and when I tested I really never thought of conflicting/overlapping events, but it makes a lot of sense.

In all honesty, I wrote this widget in 2012 and was the first widget of its kind.  Many things have changed since then, but most importantly, that I don't think this widget should be used on Android, for the reason I wrote in a previous message in this thread.

On the other hand, if that solution works for you, I'd be happy to merge it to master, but again, I think it's overkill to work around those issues when we have access to the native navigation drawer.

Best,

R
