### ISSUE TITLE
hide navbar on andriod

### ISSUE THREAD

**Issue by aqeelhashem** [ricardoalcocer/alloy-widget-drawermenu#9]
Hi, and thanks for your wonderful plugin.

when i use this widgets , there are an nav bar on the top of screen in android platform,

I don't know how to remove it , or where to put navbarhidden command.

I hope to find the answer

thanks

**Comment by aqeelhashem** [comment]
thanks I found it, in index.tss  :)

**Comment by ricardoalcocer** [comment]
Hiding the ActionBar on Android is a bit more difficult now after 3.3.0.  I blogged about it here: http://www.appcelerator.com/blog/2014/08/hiding-the-android-actionbar/.  I however, suggest that instead of trying to hide the ActionBar you should embrace it and build your user interface around it.  The /ActionBar demo folder has a demo on how to trigger the widget from the ActionBar.
